INSERT INTO umpire (umpire_id, umpire_name, country_name) values (1, 'Sundaram Ravi', 'India');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (2, 'Anil Chaudhary', 'India');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (3, 'Kumar Dharmasena', 'Sri Lanka');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (4, 'Chettithody Shamshuddin', 'India');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (5, 'Nitin Menon', 'India');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (6, 'Marais Erasmus', 'South Africa');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (7, 'C. K. Nandan', 'India');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (8, 'Chris Gaffaney', 'New Zealand');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (9, 'Vineet Kulkarni', 'India');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (10, 'Bruce Oxenford', 'Australia');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (11, 'Rod Tucker', 'Australia');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (12, 'K. N. Ananthapadmanabhan', 'India');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (13, 'Richard Illingworth', 'England');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (14, 'Nigel Llong', 'England');
INSERT INTO umpire (umpire_id, umpire_name, country_name) values (15, 'Virender Sharma', 'India');
